// <auto-generated />
namespace DeliveryService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class includedcustomerforeighnkeyintotheOrdertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(includedcustomerforeighnkeyintotheOrdertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201807121601243_included customer foreighn key into the Order table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
