// <auto-generated />
namespace DeliveryService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedtimeoftheday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedtimeoftheday));
        
        string IMigrationMetadata.Id
        {
            get { return "201807202324543_changed time of the day"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
